### ISSUE TITLE
Use "request" instead of "get"

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/node-tilejson#37]
Can the dependency on https://github.com/mapbox/node-get be replaced with https://github.com/request/request ?

As `get` is not fully supporting proxies (e.g. HTTPS url and HTTP proxy or authentication), which `request` already has ([`request#proxies`](https://github.com/request/request#proxies)),  it seems that this is the only roadblock on unleashing proxy support with Mapbox Studio.

Also, `tile-json` is the only Mapbox Studio dependency that uses `get`, all others already use `request`.

**Comment by BergWerkGIS** [comment]
@ianshward @miccolis 
/cc @springmeyer 

I made tilejson work with [`request`](https://github.com/request/request).

As I'm not the javascript guy and my goal was to `proxy-enable` Mapbox Studio my changes are really hackish, but I verified that Mapbox Studio now works with proxies. :rocket: 

The changes are minimal (not looking at some tests, where I flipped parameter as they were in the wrong order):
https://github.com/mapbox/node-tilejson/compare/master...BergWerkGIS:master

It would be great, if

* one of you could pick up this task or point me to the right person to do it (who also has an overview what other modules might be affected by this change and implement the new `asBuffer` function in a way that provides backward compatibility)
* we could make this change happen for the upcoming release of Mapbox Studio as support for proxies gets asked more and more.

**Comment by yhahn** [comment]
@BergWerkGIS I'll take a look at this this week.

**Comment by BergWerkGIS** [comment]
@yhahn :clap:

**Comment by tmcw** [comment]
:+1: This may also yield some benefits wrt getting node v0.12 support in downstream projects.

**Comment by springmeyer** [comment]
@tmcw - I think you are right. Looks like node-tilejson is currently broken with node v0.12.x: https://travis-ci.org/mapbox/node-tilejson/builds/70100324. /cc @yhahn

**Comment by springmeyer** [comment]
Going to close this:

  - master is now using `request` via the `requestretry` module - https://github.com/mapbox/node-tilejson/commit/8d6b66766852599474b35dbd23fe7c332bade562
  - one of the motivators behind switching to request is still an open issue. See https://github.com/mapbox/node-tilejson/pull/41
